export const jobCategories = [
  { id: 1, title: "Teknologi", description: "Inovasi IT", logo: "fa-solid fa-computer fa-2xl" },
  { id: 2, title: "Keuangan", description: "Manajemen Keuangan", logo: "fa-solid fa-coins fa-2xl" },
  { id: 3, title: "Kesehatan", description: "Perawatan Kesehatan", logo: "fa-solid fa-notes-medical fa-2xl" },
  { id: 4, title: "Pendidikan", description: "Pengajaran dan Pelatihan", logo: "fa-solid fa-school fa-2xl" },
  { id: 5, title: "Manufaktur", description: "Produksi Barang", logo: "fa-solid fa-industry fa-2xl" },
  { id: 6, title: "Pemasaran", description: "Pengembangan Pasar", logo: "fa-solid fa-square-poll-vertical fa-2xl" },
  { id: 7, title: "Administrasi", description: "Manajemen Kantor", logo: "fa-solid fa-file fa-2xl" },
  { id: 8, title: "Hukum", description: "Layanan Hukum", logo: "fa-solid fa-scale-balanced fa-2xl" },
  { id: 9, title: "Sumber Daya Manusia", description: "Manajemen SDM", logo: "fa-solid fa-person fa-2xl" },
  { id: 10, title: "Seni", description: "Kreativitas Seni", logo: "fa-solid fa-palette fa-2xl" },
  { id: 11, title: "Rekayasa", description: "Desain dan Konstruksi", logo: "fa-solid fa-helmet-safety fa-2xl" },
  { id: 12, title: "Layanan Pelanggan", description: "Dukungan Pelanggan", logo: "fa-solid fa-headset fa-2xl" },
  { id: 13, title: "Transportasi", description: "Logistik dan Transportasi", logo: "fa-solid fa-truck-fast fa-2xl" },
  { id: 14, title: "Pariwisata", description: "Industri Pariwisata", logo: "fa-solid fa-map-location fa-2xl" },
  { id: 15, title: "Lainnya", description: "Kategori Lainnya", logo: "fa-solid fa-lightbulb fa-2xl" },
];

export const provinces = [
  "Aceh",
  "Sumatera Utara",
  "Sumatera Barat",
  "Riau",
  "Jambi",
  "Sumatera Selatan",
  "Bengkulu",
  "Lampung",
  "Banten",
  "DKI Jakarta",
  "Jawa Barat",
  "Jawa Tengah",
  "DI Yogyakarta",
  "Jawa Timur",
  "Bali",
  "Nusa Tenggara Barat",
  "Nusa Tenggara Timur",
  "Kalimantan Barat",
  "Kalimantan Tengah",
  "Kalimantan Selatan",
  "Kalimantan Timur",
  "Kalimantan Utara",
  "Sulawesi Utara",
  "Gorontalo",
  "Sulawesi Tengah",
  "Sulawesi Selatan",
  "Sulawesi Tenggara",
  "Sulawesi Barat",
  "Maluku",
  "Maluku Utara",
  "Papua Barat",
  "Papua",
  "Lainnya",
];

export const experienceOptions = ["Tidak Ada Pengalaman (Entry-Level)", "1-2 Tahun Pengalaman", "3-5 Tahun Pengalaman", "Lebih Dari 5 Tahun Pengalaman (Pengalaman Senior)", "Terbuka untuk Semua Tingkat Pengalaman"];

export const educationOptions = ["SMA/SMK", "Diploma", "Sarjana (S1)", "Magister (S2)", "Doktor (S3)"];
